### ISSUE TITLE
UI Mockup

### ISSUE THREAD

**Issue by ysrivast2000** [CMPUT301F21T20/HabitTracker#22]
Create a UI Mockup for each user story

**Comment by CharlotteZsm** [comment]
![UIDesign](https://user-images.githubusercontent.com/56488396/137427492-eeef2865-14f0-485b-94a3-ee138edf554d.jpg)

**Comment by lujiannan** [comment]
I have done writing the story points and finish half of the UI mockups (the other half is left to Simiao)
